### ISSUE TITLE
Consider migrating to `fast-deep-equal`

### ISSUE THREAD

**Issue by toastal** [lzztt/koa-session-minimal#21]
`deep-equal` is not only [2 orders of magnitude slower](https://www.npmjs.com/package/fast-deep-equal#performance-benchmark) than [`fast-deep-equal`](https://www.npmjs.com/package/fast-deep-equal#), but it's by far the biggest [dependency tree limbs](https://npmgraph.js.org/?q=koa-session-minimal) in the project containing polyfills that haven't been needed for browsers or Node since 2015 (and your `package.json` denotes `"node": ">= 14"`). At 38M weekly downloads, it is not a small project either. Swapping dependencies to `fast-deep-equal` could save consumers kilobytes and reap a performance benefit. Transitive dependencies would go from 53 to 4.

**Comment by lzztt** [comment]
Thank you very much for the suggestion!
migrated in v4.0.3
